### PR TITLE
Run integration tests in parallel

### LINKED ISSUE #26: Run integration tests in parallel
The integration tests are doing a bunch of `kompile` and `kprove` calls, which currently are done fully serial.

All the `kompile` calls can go in parallel, and then all the `kprove` calls can go in parallel too. This should greatly reduce CI time.

### PR DESCRIPTION
**Pull request by tothtamas28**
Fixes #26

### CODE REVIEW

**Comment by ehildenb** [comment]
This is a known failure? 
image

**Comment by ehildenb** [comment]
Did you test that this is correctly propogating failures up through the Makefile? Honestly, I would prefer if the parallelism happened in the Python, not in the Makefile. This is somewhat convoluted, and I'd like a parallel way to run Python tests set up as a default anyway.

**Comment by tothtamas28** [comment]
> This is a known failure?

Yes: https://github.com/runtimeverification/pyk/issues/27

**Comment by tothtamas28** [comment]
> I would prefer if the parallelism happened in the Python, not in the Makefile. This is somewhat convoluted, and I'd like a parallel way to run Python tests set up as a default anyway.

I agree, will look into it. I'll cherry-pick the refactoring commits into another PR so that they ca be reviewed and merged until I figure out the rest. This moves back to draft.

**Pull request closed without merging**
