### PR TITLE
Fix `kast_to_kore` for `KToken`

### PR DESCRIPTION
**Pull request by tothtamas28**

### CODE REVIEW

**Review by ehildenb — APPROVED** [review]

**Comment by ehildenb** [comment]
@tothtamas28 did you test this by actually sending the produced kore into one of the backends? A string that `enquote` would change, but is not being handled correctly here? Perhaps a definition with an emoji in it, and you pass it over kore-rpc?

**Comment by tothtamas28** [comment]
> @tothtamas28 did you test this by actually sending the produced kore into one of the backends? A string that `enquote` would change, but is not being handled correctly here? Perhaps a definition with an emoji in it, and you pass it over kore-rpc?

I tried to add a test for the following definition:

```k
module EMOJI-SYNTAX
    syntax Emoji ::= r"🙁|🙂" [token]
endmodule

module EMOJI
    imports EMOJI-SYNTAX
    rule <k> 🙁 => 🙂 ... </k>
endmodule
```

and I was able to confirm that the `\dv` obtained from `kast_to_kore` passes the `kore-rpc` interface correctly in both directions. Unfortunately only by inspecting the failing test output.

The problem is that symbolic execution gets stuck in the initial configuration. When changing the tokens to `1` and `2` it works fine, so I don't think it's an issue in the test setup. I checked `compiled.txt` and the generated rule looks weird to me, as if things didn't get tokenized correctly:

```
  rule `<generatedTop>`(`<k>`(``#token("\U0001f641 =","Emoji")=>#token(" ...","Emoji")``~>_DotVar1),_DotVar0) requires #token("true","Bool") ensures #token("true","Bool") [...]
```

`EMOJI-SYNTAX` looks ok:

```k
  syntax Emoji ::= r"\U0001f641|\U0001f642" [token]
```

@radumereuta, is there a bug here?

**Comment by radumereuta** [comment]
I tried parsing an emoji with your example and I got an error from kast:
```console
$ kast 2.test --debug
java.lang.StringIndexOutOfBoundsException: begin 0, end 4, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.kframework.parser.inner.kernel.EarleyParser.wrapState(EarleyParser.java:343)
	at org.kframework.parser.inner.kernel.EarleyParser$EarleySet.add(EarleyParser.java:492)
	at org.kframework.parser.inner.kernel.EarleyParser.addStateToSet(EarleyParser.java:971)
	at org.kframework.parser.inner.kernel.EarleyParser.scan(EarleyParser.java:948)
	at org.kframework.parser.inner.kernel.EarleyParser.parse(EarleyParser.java:833)
	at org.kframework.parser.inner.ParseInModule.parseStringTerm(ParseInModule.java:237)
	at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:200)
	at org.kframework.parser.inner.ParseInModule.parseString(ParseInModule.java:165)
	at org.kframework.kompile.CompiledDefinition.parseSingleTerm(CompiledDefinition.java:213)
	at org.kframework.parser.KRead.prettyRead(KRead.java:66)
	at org.kframework.parser.KRead.prettyRead(KRead.java:54)
	at org.kframework.kast.KastFrontEnd.run(KastFrontEnd.java:215)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:57)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type
StringIndexOutOfBoundsException (StringIndexOutOfBoundsException: begin 0, end
4, length 2)
```
Something is definitely wrong. What is your workflow?

**Comment by tothtamas28** [comment]
> Something is definitely wrong. What is your workflow?

1) `kompile --backend haskell`
2)  Start `kore-rpc` with `definition.kore`
3) Invoke `execute` endpoint with pattern (using the JSON representation of course):

```kore
Lbl'-LT-'generatedTop'-GT-'{} (
    Lbl'-LT-'k'-GT-'{} (
        kseq{} (
            inj{SortEmoji{}, SortKItem{}} (
                \dv{SortEmoji{}} ("\U0001f641")
            ),
            dotk{} ()
        )
    ),
    Lbl'-LT-'generatedCounter'-GT-'{} (
         \dv{SortInt{}} ("0")
    )
)
```

**Comment by radumereuta** [comment]
Kompile fails to parse the emojis correctly:
```
// rules
// rule `<generatedTop>`(`<k>`(inj{Emoji,KItem}(#token("\U0001f641 =","Emoji"))~>_DotVar1),_DotVar0)=>`<generatedTop>`(`<k>`(inj{Emoji,KItem}(#token(" ...","Emoji"))~>_DotVar1),_DotVar0) requires #token("true","Bool") ensures #token("true","Bool") [UNIQUE_ID(6118c5ab7e8dfbb748a6cabd2735315fbb40a34be6e21ac91549ff7a092e0b44), org.kframework.attributes.Location(Location(7,10,7,27)), org.kframework.attributes.Source(Source(/home/radu/work/test/test.k)), org.kframework.definition.Production(syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol])]
  alias rule0LHS{}(SortGeneratedCounterCell{},SortK{}) : SortGeneratedTopCell{}
  where rule0LHS{}(Var'Unds'DotVar0:SortGeneratedCounterCell{},Var'Unds'DotVar1:SortK{}) :=
    \and{SortGeneratedTopCell{}} (
      \top{SortGeneratedTopCell{}}(), Lbl'-LT-'generatedTop'-GT-'{}(Lbl'-LT-'k'-GT-'{}(kseq{}(inj{SortEmoji{}, SortKItem{}}(\dv{SortEmoji{}}("\U0001f641 =")),Var'Unds'DotVar1:SortK{})),Var'Unds'DotVar0:SortGeneratedCounterCell{})) []
```

**Comment by tothtamas28** [comment]
> I think this can be merged in the meantime, but yes, let's open an issue against the frontend with the minimal example.

https://github.com/runtimeverification/k/issues/3086

**Pull request merged**
