### PR TITLE
Add logs for kore-rpc calls and KCFG nodes

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
This PR implements the proposed changes in https://github.com/runtimeverification/pyk/issues/393, namely:

* Add `LogEntry` class to `kore.rpc` which holds the logging data returned from the rpc server execute endpoint
* Add `logs` attribute to the `ExecuteResult` as well as `ImpliesResult` and the simplify rpc endpoint (the last two require https://github.com/runtimeverification/haskell-backend/pull/3580 to be merged)
* Store the logs inside the KCFG `Node` for analysis via the kcfg-viewer (will be implemented in a followup PR)

### CODE REVIEW

**Comment by goodlyrottenapple** [comment]
This is just a draft atm as I've not tested this yet. Just wanted to see if my approach is correct.

**Comment by ehildenb** [comment]
I think we should also attach the same logs to `simplify` endpoint and `check-implication` endpoint, so that we can get the equations applied while trying to do those routines.

It can be the same thing where we make best effort to have the old backend fill in those data, but prioritize the new backend filling in those data when those endpoints come available in the new backend.

**Comment by ehildenb** [comment]
Rather than attaching the logs to the KCFG, I would rather have the `KCFGExplore` class track the logs external to the `KCFG` datastructure. So the calles `KCFGExplore.cterm_*` ... return a `tuple[result, LOGS]`. Then teh user can decide what to do with those log entries, and store them in a more appropriate datastructure.

**Comment by ehildenb** [comment]
For this PR, let's just have the various `KCFGExplore.cterm_*` methods take an extra `log: bool = False` option, and return the logs as part of their return type (in a `tuple[ORIGINAL_RETURN_TYPE, Iterable[Log] | None]`). Then we can get this merged, and @geo2a is working on overhauling teh KCFG viewers to be more specific to the proof types: https://github.com/runtimeverification/pyk/issues/413, where we can incorporate a "debug" view to show the log output.

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
